import React,{useState as S,useEffect as E} from 'react';import{createRoot}from'react-dom/client';import'./style.css';
const base=['Œufs','Tomates','Courgettes','Fromage','Poulet','Pâtes','Ail','Crème'];
const data=[['Pâtes crémeuses au poulet','🍝',20,['Pâtes','Poulet','Crème','Fromage','Ail'],['Cuire les pâtes.','Faire revenir le poulet et l’ail.','Ajouter crème et fromage.','Mélanger et servir.'],'pates cremeuses poulet recette'],['Frittata courgettes & tomates','🍳',25,['Œufs','Courgettes','Tomates','Fromage'],['Faire revenir les légumes.','Battre les œufs et verser dans la poêle.','Ajouter le fromage et cuire doucement.'],'frittata courgettes tomates'],['Omelette au fromage','🥚',10,['Œufs','Fromage'],['Battre les œufs.','Cuire à la poêle avec le fromage.'],'omelette fromage recette'],['Poulet à la tomate','🍅',25,['Poulet','Tomates','Ail'],['Dorer le poulet.','Ajouter tomates et ail.','Laisser mijoter jusqu’à cuisson.'],'poulet tomate recette']];
function App(){let [page,P]=S('home'),[foods,F]=S(JSON.parse(localStorage.foods||'null')||base),[xp,X]=S(+(localStorage.xp||0)),[photo,PH]=S(''),[add,A]=S(''),[idx,I]=S(0),[done,D]=S(false);E(()=>{localStorage.foods=JSON.stringify(foods);localStorage.xp=xp},[foods,xp]);let rec=data.map(r=>({...r,have:r[3].filter(x=>foods.includes(x)).length})).filter(r=>r.have).sort((a,b)=>b.have/b[3].length-a.have/a[3].length),r=rec[idx%Math.max(1,rec.length)]||data[0];function surprise(){I(Math.floor(Math.random()*Math.max(1,rec.length)));D(false);P('recipe')}function nav(x){P(x);window.scrollTo(0,0)}return <div className="app"><header><b>👨‍🍳 Chef Maison</b><strong>⭐ {xp} XP</strong></header>
{page==='home'&&<main><label>TON COMPAGNON DE CUISINE</label><h1>Qu’est-ce qu’on cuisine ?</h1><p>Montre-moi ton frigo et je te trouve quelque chose de bon. 👀</p><div className="mascot">👨‍🍳</div><button className="primary" onClick={()=>nav('scan')}>📸 Scanner mon frigo</button><button onClick={surprise}>🎲 Surprends-moi</button><article><b>🔥 Défi du jour</b><h3>Mission anti-gaspi</h3>Utilise 2 ingrédients que tu as déjà.<small>+50 XP quand tu cuisines</small></article><h2>Ton frigo · {foods.length} aliments</h2><div className="chips">{foods.map(x=><span>{x}</span>)}</div></main>}
{page==='scan'&&<main><h1>Montre-moi ton frigo 👀</h1><p>Prends une photo, puis vérifie et corrige les aliments ci-dessous.</p><label className="upload">📷 Prendre une photo<input type="file" accept="image/*" capture="environment" onChange={e=>{if(e.target.files[0])PH(URL.createObjectURL(e.target.files[0]))}}/></label>{photo&&<img className="preview" src={photo}/>}<aside>🔎 La détection automatique par IA sera connectée au backend sécurisé. Pour l’instant, ajoute ou retire les aliments manuellement.</aside><h2>Ingrédients</h2><div className="chips">{foods.map(x=><button className="chip" onClick={()=>F(foods.filter(y=>y!==x))}>{x} ×</button>)}</div><div className="add"><input value={add} placeholder="Ajouter un ingrédient" onChange={e=>A(e.target.value)}/><button onClick={()=>{if(add.trim())F([...foods,add.trim()]);A('')}}>Ajouter</button></div><button className="primary" onClick={()=>nav('recipes')}>🍳 Voir mes recettes</button></main>}
{page==='recipes'&&<main><label>{rec.length} IDÉES POUR TOI</label><h1>À table !</h1>{rec.map((v,i)=><article className="recipe" onClick={()=>{I(i);D(false);nav('recipe')}}><span>{v[1]}</span><div><b>{v[0]}</b><small>{v[2]} min · {v.have}/{v[3].length} ingrédients disponibles</small></div>›</article>)}<button className="primary" onClick={surprise}>🎲 Surprends-moi</button></main>}
{page==='recipe'&&<main><button onClick={()=>nav('recipes')}>← Retour</button><div className="mascot">{r[1]}</div><label>{r.have}/{r[3].length} INGRÉDIENTS DISPONIBLES</label><h1>{r[0]}</h1><p>{r[2]} min · Facile</p><article><h2>Dans ton frigo</h2><div className="chips">{r[3].map(x=><span className={foods.includes(x)?'yes':'missing'}>{foods.includes(x)?'✓':'＋'} {x}</span>)}</div></article><article><h2>Préparation</h2>{r[4].map((s,i)=><p>{i+1}. {s}</p>)}</article><a className="primary link" target="_blank" href={'https://www.youtube.com/results?search_query='+encodeURIComponent(r[5])}>🎥 Voir les tutos YouTube</a><button onClick={()=>{X(xp+50);D(true)}}>{done?'🎉 Recette validée !':"✅ J’ai cuisiné ! +50 XP"}</button>{done&&<aside>Bravo chef ! 50 XP ajoutés. 🏅</aside>}</main>}
{page==='challenge'&&<main><label>DÉFI DU JOUR</label><h1>🔥 Mission anti-gaspi</h1><div className="mascot">🥕</div><article>Prépare une recette avec au moins deux ingrédients de ton frigo.<h3>Récompense : +50 XP</h3></article><button className="primary" onClick={()=>nav('recipes')}>Relever le défi</button></main>}
{page==='profile'&&<main><label>PASSEPORT DE CHEF</label><h1>Ton aventure culinaire</h1><div className="mascot">👨‍🍳</div><article><h2>⭐ {xp} XP</h2>Chaque recette cuisinée fait progresser ton passeport.</article><article><h2>🏅 Collections</h2><div className="chips"><span>🥚 Œufs</span><span>🍝 Pâtes</span><span>♻️ Anti-gaspi</span></div></article></main>}
<nav>{[['home','🏠','Accueil'],['scan','📸','Scanner'],['challenge','🔥','Défi'],['profile','👤','Passeport']].map(([id,em,t])=><button onClick={()=>nav(id)}>{em}<small>{t}</small></button>)}</nav></div>}if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js'));createRoot(document.getElementById('root')).render(<App/>);